AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance without anything else

Resources:

  SimpleEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-098c93bd9d119c051
      InstanceType: t2.micro
      KeyName: key-037c22ace9759ceee
      AvailabilityZone: eu-central-1a
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
